repos:
  - repo: https://github.com/psf/black
    rev: 21.5b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        exclude: CLAM
        args: ["--allow-untyped-globals", "--ignore-missing-imports", "--allow-untyped-defs"]

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0 # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        types: [python]
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        args:
          [
            "--ignore=E251,E266,E401,E126,E124,C901,E203,E266,E501,W503,W504,F403,F401",
          ]