python CLAM/create_splits_seq.py --task task_1_camelyon16_vit_categorical
python CLAM/create_splits_seq.py --task task_1_camelyon16_resnet_categorical
python CLAM/create_splits_seq.py --task task_1_camelyon16_kimianet_categorical
python CLAM/create_splits_seq.py --task task_1_camelyon16_custom_ssl_categorical